### ISSUE TITLE
Installation how to

### ISSUE THREAD

**Issue by SKJoy** [Slenderman00/vsirc#3]
Forgive my ignorance please.

How do I install this to VS Code on Windows 7? I don't see a VSIX package anywhere.

TIA

**Comment by Slenderman00** [comment]
Yeah, you have to compile it yourself, atm. I can add a vsix package to it tomorrow

**Comment by Slenderman00** [comment]
https://github.com/Slenderman00/vsirc/releases/tag/1.0.2
Heres the first release enjoy.

**Comment by Slenderman00** [comment]
I also published it to the vscode market place

**Comment by SKJoy** [comment]
You are wonderful. It works, of course still a lot to come and looking forward to it.
